_target_: tava.reorg.models.nerfs.nerf.NerfModel
_recursive_: false

defaults:
  - encoder/warp_dnerf@pos_enc
  - encoder/sinusoidal@view_enc
  - _self_
  
nets:
- _target_: tava.reorg.models.modules.NerfMLP
- _target_: tava.reorg.models.modules.NerfMLP

view_enc:
  max_deg: 4