_target_: tava.reorg.models.nerfs.nerf.NerfModel
_recursive_: false

defaults:
  - encoder/warp_nerfies@pos_enc
  - encoder/sinusoidal@view_enc
  - _self_

nets:
- _target_: tava.reorg.models.modules.NerfMLP
- _target_: tava.reorg.models.modules.NerfMLP

pos_enc:
  warp_meta_encoder:
    num_embeddings: 200