_target_: "tava.reorg.models.encoder.warp_se3.SE3Encoder"
_recursive_: false

_x_dim: 3  # must be 3 for now
_warp_x_min_deg: 0
_warp_x_max_deg: 8

warp_x_encoder:
  _target_: "tava.reorg.models.encoder.annealed.AnnealedSinusoidalEncoder"
  x_dim: ${_x_dim}
  min_deg: ${_warp_x_min_deg}
  max_deg: ${_warp_x_max_deg}
  use_identity: True
  alpha_sched: 
    _target_: "tava.reorg.utils.schedules.LinearSchedule"
    initial_value: ${_warp_x_min_deg}
    final_value: ${_warp_x_max_deg}
    num_steps: 80000
  
warp_meta_encoder:
  _target_: "tava.reorg.models.encoder.embed.EmbedEncoder"
  num_embeddings: 10 # dataset.num_frames
  embedding_dim: 8

x_encoder:
  _target_: "tava.reorg.models.encoder.base.SinusoidalEncoder"
  x_dim: ${_x_dim}
  min_deg: 0
  max_deg: 10  # sometimes nerfies use 8
  use_identity: True

trunk:
  _target_: "tava.reorg.models.modules.MLP"
  input_dim: ???  # warp_x_encoder.latent_dim + warp_meta_encoder.latent_dim
  net_depth: 6
  net_width: 128
  output_enabled: false
  
branch_r:
  _target_: "tava.reorg.models.modules.MLP"
  input_dim: ???  # trunk.output_dim
  output_dim: 3
  net_depth: 0
  output_init: 
    _target_: "tava.reorg.utils.hydra.partial"
    _partial_: "torch.nn.init.uniform_"
    b: 1e-4

branch_t:
  _target_: "tava.reorg.models.modules.MLP"
  input_dim: ???  # trunk.output_dim
  output_dim: 3
  net_depth: 0
  output_init: 
    _target_: "tava.reorg.utils.hydra.partial"
    _partial_: "torch.nn.init.uniform_"
    b: 1e-4

