# A basic config shared by others.

distributed: true
resume: false
resume_step: null
resume_dir: null

lr_init: 0.0005
lr_final: 0.000005
lr_delay_steps: 2500
lr_delay_mult: 0.01
max_steps: 300_000
weight_decay_mult: 0.0

percision: float32
print_every: 100
save_every: 1000
test_chunk: 512
eval_every: 10_000
eval_splits: []
eval_per_gpu: 2
eval_cache_dir: "eval_imgs_otf"
compute_metrics: true
train_split: ???

engine: ???
model: ???
dataset: ???

hydra:
  output_subdir: null
  job:
    name: "reorg"
    config:
      override_dirname:
        # Those keys do not affect the model performance so we
        # exclude them from the `override_dirname`, that would
        # affect the saving directory `run.dir`. This means other
        # than the keys listed here, other keys you set thru
        # command line would decide which directory to save / load
        # the model.
        exclude_keys:
          - model
          - dataset  # already included in the run.dir
          - dataset.subject_id  # already included in the run.dir
          - dataset.root_fp
          - distributed
          - resume
          - resume_step
          - resume_dir
          - print_every
          - save_every
          - test_chunk
          - eval_every
          - eval_splits
          - eval_per_gpu
          - eval_cache_dir
  run:
    # set the saving / loading directory
    dir: "outputs/\
      ${hydra.job.name}/
      ${hydra.runtime.choices.model}/\
      ${hydra.runtime.choices.dataset}/\
      ${dataset.subject_id}/\
      cfg=${hydra.job.override_dirname}/\
      "
